name: Modify Repository Permissions

on:
  schedule:
    - cron: '0 0 * * 1' # Ejecuta todos los lunes a medianoche UTC
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

permissions:
  contents: write  # Ajustar permisos segÃºn sea necesario

jobs:
  modify-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Upload JSON configuration file
        uses: actions/upload-artifact@v3
        with:
          name: repos-config
          path: repos.json

      - name: Set up GitHub App token
        id: my-app
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.DELETEMEPLEASESTEMDO_APP_ID }}
          private_key: ${{ secrets.DELETEMEPLEASESTEMDO_PRIVATE_KEY }}

      - name: Modify repository permissions
        id: modify-permissions
        env:
          TOKEN: ${{ steps.my-app.outputs.token }}
        run: |
          node modify-permissions.js

      - name: Create Summary
        if: always()
        run: |
          echo "${{ steps.modify-permissions.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
